## Common

# This prefix is prepended to routes across all services when supplied.
api:
  base-path: "/api"


## Admin Service
#  -------------
# NOTE: Where possible, we support the configuration variables declared for micronaut-kafka in their Consumer/Producer
# implementation to retain portability of config.
# See Also: https://micronaut-projects.github.io/micronaut-kafka/1.1.x/guide/index.html
kafka:

  bootstrap:
    servers: localhost:9092
  #  ssl:
  #    keystore:
  #      location: /path/to/client.keystore.p12
  #      password: secret
  #    truststore:
  #      location: /path/to/client.truststore.jks
  #      password: secret
  #      type: PKCS12
  #  security:
  #    protocol: ssl

## SAML2 Micronaut Security Spec (Testing Only)
## --------------------------------
#
micronaut:
  security:
    enabled: true
    saml2:
      enabled: true
#      contacts:
#
      services:
        microsoft:
          idp:
            entityid: "<AAD Tenant Endpoint EntityID>"
            sso-url: "<AAD Tenant SSO URL>"
            slo-url: "<AAD Tenant SLO URL>"
            certificate: "<Base64 Encoded DER Cert>"

          sp:
            entityid: "<AAD App Registration Client ID>"
            assertion-consumer-path: /saml2/acs/microsoft
            nameid-format: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
